---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.basename }}
  labels:
    app.kubernetes.io/name: {{ .Values.basename }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.basename }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.basename }}
    spec:
      containers:
        - name: {{ .Values.basename }}
          image: hazelcast/hazelcast:4.2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5701
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.basename }}-mng
  labels:
    app.kubernetes.io/name: {{ .Values.basename }}-mng
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.basename }}-mng
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.basename }}-mng
    spec:
      containers:
        - name: {{ .Values.basename }}-mng
          image: hazelcast/management-center:4.2021.06
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.mngPort }}
          env:
          - name: HZ_MC_CLUSTER
            value: dev
          - name: HZ_MC_MEMBERS
            value: hazelcast
          command: ["bash", "-c", "set -euo pipefail && ./bin/mc-conf.sh cluster add --cluster-name=\"${HZ_MC_CLUSTER}\" --member-addresses=\"${HZ_MC_MEMBERS}\" && ./bin/mc-start.sh"]
